const allOrders = [
  {
    id: 1,
    user: "ana",
    name: "pizza",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "pizza",
  },
  {
    id: 2,
    user: "ana",
    name: "juice",
    amount: `1`,
    note: "lorem, lorem",
    price: 350,
    category: "drinks",
  },
  {
    id: 5,
    user: "aca",
    name: "coca-cola",
    amount: `1`,
    note: "lorem, lorem",
    price: 400,
    category: "drinks",
  },
  {
    id: 5,
    user: "aca",
    name: "pizza",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "pizza",
  },
  {
    id: 5,
    user: "anita",
    name: "krem-plazma",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "pancakes",
  },
  {
    id: 6,
    user: "maja",
    name: "burito",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "burito",
  },
  {
    id: 7,
    user: "maja",
    name: "cheesburger",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "burgers",
  },
  {
    id: 8,
    user: "anita",
    name: "pljeskavica",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "barbecue",
  },
  {
    id: 9,
    user: "anita",
    name: "pasta",
    amount: `1`,
    note: "lorem, lorem",
    price: 300,
    category: "pasta",
  },
];

export default allOrders;
